---
- name: "Install httpd and start the service"
  hosts: all
  gather_fact: false
  tasks:
  - name: install HTTPD
    yum: 
      name: httpd
      state: latest 
  - name: start service
    service:
      name: httpd
      state: latest 
